version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  webapp:
    build: .
    image: webapp_image
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=5000
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo_container
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
